# Generated by Django 3.2.9 on 2021-11-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_somemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='somemodel',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
