# Generated by Django 3.2.9 on 2021-11-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_somemodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
