# Generated by Django 3.2.9 on 2021-11-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_delete_somemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
